[project]
name = "projet-ia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sarah", email = "sbruyere001@ensc.fr" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost>=3.2.0",
]

[project.scripts]
projet-ia = "projet_ia:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
